foyer-rs/mixtrics

Cargo.toml
=> chore: add crate desc

.github/workflows/ci.yml, .vscode/settings.json, Cargo.toml, Makefile, README.md, src/registry/mod.rs, src/registry/prometheus_client_0_23.rs
=> feat: support prometheus-client 0.23

Cargo.toml, README.md
=> chore: release v0.0.1

src/registry/prometheus_client_0_23.rs
=> fix: fix prometheus-client 0.23 support

.github/workflows/ci.yml, .vscode/settings.json, Cargo.toml, Makefile, src/lib.rs, src/registry/prometheus_client_0_23.rs, src/test_utils.rs
Signed-off-by: MrCroxx <mrcroxx@outlook.com>## What's changed and what's your intention?
As title.
close #5
=> feat: introduce test utils

Cargo.toml, Makefile, src/utils.rs
=> chore: release v0.0.2

Cargo.toml, README.md
=> chore: release mixtrics v0.0.3

src/metrics.rs, src/registry/noop.rs, src/registry/opentelemetry_0_26.rs, src/registry/opentelemetry_0_27.rs, src/registry/prometheus.rs, src/registry/prometheus_client_0_22.rs, src/registry/prometheus_client_0_23.rs
As title.
https://github.com/foyer-rs/foyer/issues/894
=> feat: support customized histogram buckets

src/metrics.rs
As title.
https://github.com/foyer-rs/foyer/issues/894
=> feat: add buckets helper

Cargo.toml
=> chore: release mixtrics v0.0.4

.vscode/settings.json, Cargo.toml, README.md, src/registry/mod.rs, src/registry/opentelemetry_0_28.rs, src/registry/opentelemetry_0_29.rs, src/test_utils.rs
Signed-off-by: MrCroxx <mrcroxx@outlook.com>## What's changed and what's your intention?
As title.
=> feat: support opentelemetry 0.28 and 0.29

Cargo.toml
=> chore: release mixtrics v0.0.5

.vscode/settings.json, Cargo.toml, README.md, src/registry/mod.rs, src/registry/prometheus_0_13.rs, src/registry/prometheus_0_14.rs, src/test_utils.rs
=> feat: support prometheus 0.14

Cargo.toml
=> chore: release mixtrics v0.0.6

.github/workflows/ci.yml, Cargo.toml, Makefile, README.md, examples/basic.rs
=> doc: add examples and update readme

CHANGELOG.md, Cargo.toml, README.md
=> chore: release mixtrics v0.1.0

.github/workflows/ci.yml, Cargo.toml, src/registry/mod.rs, src/registry/opentelemetry_0_30.rs, src/test_utils.rs
=> feat: support opentelemetry v0.30.x

Cargo.toml
=> chore: release mixtrics v0.2.0

README.md
=> chore: add otel 0.30 support in readme

CHANGELOG.md, Cargo.toml, README.md, src/registry/mod.rs, src/registry/opentelemetry_0_31.rs, src/test_utils.rs
=> feat: support opentelemetry v0.31.x
